server {
    listen 80;
    listen [::]:80;
    server_name ymihh.xyz www.ymihh.xyz;
    root /srv/garden/current/dist;
    location ^~ /.well-known/acme-challenge/ { root /var/www/letsencrypt; }
    location / { try_files $uri $uri/ =404; }
}
